<?php
//-------------------------------------------------------------database connection-------------------------------------------
include("database_connection.php");

$kids_wear = "create table kidswear(productId varchar(20) primary key, image varchar(200), name varchar(100), price varchar(10), size varchar(10), quantity varchar(10), description varchar(200))";
$con->query($kids_wear);
$w1 = "insert into kidswear values('kwc1p1ss', 'assets/49.jpeg', 'Full Sleeve Printed Boys Sweatshirt', '2100', 'S', '1100', 'With a rainbow of colors available and a budget-friendly price point, this hoodie can't be beat!.')";
$con->query($w1);
$w2 = "insert into kidswear values('kwc1p1sm', 'assets/49.jpeg', 'Full Sleeve Printed Boys Sweatshirt', '2100', 'M', '1100', 'With a rainbow of colors available and a budget-friendly price point, this hoodie can't be beat!.')";
$con->query($w2);
$w3 = "insert into kidswear values('kwc1p1sl', 'assets/49.jpeg', 'Full Sleeve Printed Boys Sweatshirt', '2100', 'L', '1100', 'With a rainbow of colors available and a budget-friendly price point, this hoodie can't be beat!.')";
$con->query($w3);
$w4 = "insert into kidswear values('kwc1p2ss', 'assets/50.jpeg', 'Full Sleeve Boys Sweatshirt', '2500', 'S', '1100', 'Crafted from 100% cotton this sweatshirt from the AW18 Dsquared2 kids collection')";
$con->query($w4);
$w5 = "insert into kidswear values('kwc1p2sm', 'assets/50.jpeg', 'Full Sleeve Boys Sweatshirt', '2500', 'M', '1100', 'Crafted from 100% cotton this sweatshirt from the AW18 Dsquared2 kids collection')";
$con->query($w5);
$w6 = "insert into kidswear values('kwc1p2sl', 'assets/50.jpeg', 'Full Sleeve Boys Sweatshirt', '2500', 'L', '1100', 'Crafted from 100% cotton this sweatshirt from the AW18 Dsquared2 kids collection')";
$con->query($w6);
$w7 = "insert into kidswear values('kwc1p3ss', 'assets/51.jpeg', 'Full Sleeve Embellished Sweatshirt', '2700', 'S',  '1100', 'Full Sleeve Embellished Sweatshirt Great sweatshirt from the latest collection.')";
$con->query($w7);
$w8 = "insert into kidswear values('kwc1p3sm', 'assets/51.jpeg', 'Full Sleeve Embellished Sweatshirt', '2700', 'M', '1100', 'Full Sleeve Embellished Sweatshirt Great sweatshirt from the latest collection.')";
$con->query($w8);
$w9 = "insert into kidswear values('kwc1p3sl', 'assets/51.jpeg', 'Full Sleeve Embellished Sweatshirt', '2700', 'L', '1100', 'Full Sleeve Embellished Sweatshirt Great sweatshirt from the latest collection.')";
$con->query($w9);
$w10 = "insert into kidswear values('kwc2p1ss', 'assets/52.jpg', 'Boys Printed Pure Cotton T Shirt', '3000', 'S', '1100', 'Wild Thunder T Shirt - Premium Quality Half Sleeve Round Neck Plain 100% Cotton Durable High Quality Crew neck for Kids.')";
$con->query($w10);
$w11 = "insert into kidswear values('kwc2p1sm', 'assets/52.jpg', 'Boys Printed Pure Cotton T Shirt', '3000', 'M', '1100', 'Wild Thunder T Shirt - Premium Quality Half Sleeve Round Neck Plain 100% Cotton Durable High Quality Crew neck for Kids.')";
$con->query($w11);
$w12 = "insert into kidswear values('kwc2p1sl', 'assets/52.jpg', 'Boys Printed Pure Cotton T Shirt', '3000', 'L', '1100', 'Wild Thunder T Shirt - Premium Quality Half Sleeve Round Neck Plain 100% Cotton Durable High Quality Crew neck for Kids.')";
$con->query($w12);
$w13 = "insert into kidswear values('kwc2p2ss', 'assets/53.jpg', 'Girls Party Cotton Blend Top', '2800', 'S', '1100', 'Premium Quality Cotton tshirt Round neck t shirt Short sleeve t-shirt Silk screen printed tshirts .')";
$con->query($w13);
$w14 = "insert into kidswear values('kwc2p2sm', 'assets/53.jpg', 'Girls Party Cotton Blend Top', '2800', 'M', '1100', 'Premium Quality Cotton tshirt Round neck t shirt Short sleeve t-shirt Silk screen printed tshirts .')";
$con->query($w14);
$w15 = "insert into kidswear values('kwc2p2sl', 'assets/53.jpg', 'Girls Party Cotton Blend Top', '2800', 'L', '1100', 'Premium Quality Cotton tshirt Round neck t shirt Short sleeve t-shirt Silk screen printed tshirts .')";
$con->query($w15);
$w16 = "insert into kidswear values('kwc2p3ss', 'assets/54.jpg', 'Boys & Girls Printed Cotton Silk T Shirt', '3200', 'S', '1100', 'Soft feel comfort Tshirt kids Tshirt for kids Kids 1-15 years old Comfortable and Durable High Quality Crew neck.')";
$con->query($w16);
$w17 = "insert into kidswear values('kwc2p3sm', 'assets/54.jpg', 'Boys & Girls Printed Cotton Silk T Shirt', '3200', 'M', '1100', 'Soft feel comfort Tshirt kids Tshirt for kids Kids 1-15 years old Comfortable and Durable High Quality Crew neck.')";
$con->query($w17);
$w18 = "insert into kidswear values('kwc2p3sl', 'assets/54.jpg', 'Boys & Girls Printed Cotton Silk T Shirt', '3200', 'L', '1100', 'Soft feel comfort Tshirt kids Tshirt for kids Kids 1-15 years old Comfortable and Durable High Quality Crew neck.')";
$con->query($w18);
$w19 = "insert into kidswear values('kwc3p1ss', 'assets/58.jpg', 'Girls Pink Jacket', '4200', 'S', '1100', 'Burberry baby girls pink quilted jacket with a hood, an embossed flap over the zip closure, three buttoned pockets on the front.')";
$con->query($w19);
$w20 = "insert into kidswear values('kwc3p1sm', 'assets/58.jpg', 'Girls Pink Jacket', '4200', 'M', '1100', 'Burberry baby girls pink quilted jacket with a hood, an embossed flap over the zip closure, three buttoned pockets on the front.')";
$con->query($w20);
$w21 = "insert into kidswear values('kwc3p1sl', 'assets/58.jpg', 'Girls Pink Jacket', '4200', 'L', '1100', 'Burberry baby girls pink quilted jacket with a hood, an embossed flap over the zip closure, three buttoned pockets on the front.')";
$con->query($w21);
$w22 = "insert into kidswear values('kwc3p2ss', 'assets/59.jpg', 'Black Jacket', '4000', 'S', '1100', 'This adorable and soft monogrammed sherpa jacket will keep your kids warm during those chilly fall and winter mornings boys space jacket, modeled after Alpha’s jacket.')";
$con->query($w22);
$w23 = "insert into kidswear values('kwc3p2sm', 'assets/59.jpg', 'Black Jacket', '4000', 'M', '1100', 'This adorable and soft monogrammed sherpa jacket will keep your kids warm during those chilly fall and winter mornings boys space jacket, modeled after Alpha’s jacket .')";
$con->query($w23);
$w24 = "insert into kidswear values('kwc3p2sl', 'assets/59.jpg', 'Black Jacket', '4000', 'L', '1100', 'This adorable and soft monogrammed sherpa jacket will keep your kids warm during those chilly fall and winter mornings boys space jacket, modeled after Alpha’s jacket .')";
$con->query($w24);
$w25 = "insert into kidswear values('kwc3p3ss', 'assets/60.jpg', 'Black rugged Jacket', '3500', 'S', '1100', 'This rugged jacket offers waterproof, lightly insulated coverage that lets kids have fun outdoors even when conditions aren't perfect.')";
$con->query($w25);
$w26 = "insert into kidswear values('kwc3p3sm', 'assets/60.jpg', 'Black rugged Jacket', '3500', 'M', '1100', 'This rugged jacket offers waterproof, lightly insulated coverage that lets kids have fun outdoors even when conditions aren't perfect.')";
$con->query($w26);
$w27 = "insert into kidswear values('kwc3p3sl', 'assets/60.jpg', 'Black rugged Jacket', '3500', 'L', '1100', 'This rugged jacket offers waterproof, lightly insulated coverage that lets kids have fun outdoors even when conditions aren't perfect.')";
$con->query($w27);
$w28 = "insert into kidswear values('kwc4p1ss', 'assets/55.jpg', 'Sports Pants', '2500', 'S', '1100', 'Spring Boys Elastic Loose Pants Colored Sports Pants For Girls Children Sweatpants Kids Trousers 2-12Y Baby Clothing Top-Quality.')";
$con->query($w28);
$w29 = "insert into kidswear values('kwc4p1sm', 'assets/55.jpg', 'Sports Pants', '2500', 'M', '1100', 'Spring Boys Elastic Loose Pants Colored Sports Pants For Girls Children Sweatpants Kids Trousers 2-12Y Baby Clothing Top-Quality.')";
$con->query($w29);
$w30 = "insert into kidswear values('kwc4p1sl', 'assets/55.jpg', 'Sports Pants', '2500', 'L', '1100', 'Spring Boys Elastic Loose Pants Colored Sports Pants For Girls Children Sweatpants Kids Trousers 2-12Y Baby Clothing Top-Quality.')";
$con->query($w30);
$w31 = "insert into kidswear values('kwc4p2ss', 'assets/57.jpg', 'Track Pant For Boys & Girls', '2700', 'S', '1100', 'This pants feature a side pockets and letter print design.amde by natural synthetic comfortable design.')";
$con->query($w31);
$w32 = "insert into kidswear values('kwc4p2sm', 'assets/57.jpg', 'Track Pant For Boys & Girls', '2700', 'M', '1100', 'This pants feature a side pockets and letter print design.amde by natural synthetic comfortable design.')";
$con->query($w32);
$w33 = "insert into kidswear values('kwc4p2sl', 'assets/57.jpg', 'Track Pant For Boys & Girls', '2700', 'L', '1100', 'This pants feature a side pockets and letter print design.amde by natural synthetic comfortable design.')";
$con->query($w33);
$w34 = "insert into kidswear values('kwc4p3ss', 'assets/56.jpg', 'kids pant', '2800', 'S', '1100', 'Fashion Kids Leisure Pants 2-7Y Casual Baby Trousers Spring Autumn Toddler Baby Boys Pants Children Clothing Summer boys pants wholesale casual kids trousers.')";
$con->query($w34);
$w35 = "insert into kidswear values('kwc4p3sm', 'assets/56.jpg', 'kids pant', '2800', 'M', '1100', 'Fashion Kids Leisure Pants 2-7Y Casual Baby Trousers Spring Autumn Toddler Baby Boys Pants Children Clothing Summer boys pants wholesale casual kids trousers..')";
$con->query($w35);
$w36 = "insert into kidswear values('kwc4p3sl', 'assets/56.jpg', 'kids pant', '2800', 'L', '1100', 'Fashion Kids Leisure Pants 2-7Y Casual Baby Trousers Spring Autumn Toddler Baby Boys Pants Children Clothing Summer boys pants wholesale casual kids trousers.')";
$con->query($w36);
?>
