<?php
//-------------------------------------------------------------database connection-------------------------------------------
include("database_connection.php");

$women_wear = "create table womenwear(productId varchar(20) primary key, image varchar(200), name varchar(100), price varchar(10), size varchar(10), quantity varchar(10), description varchar(200))";
$con->query($women_wear);
$w1 = "insert into womenwear values('wwc1p1ss', 'assets/11.jpeg', 'Mini Dress', '2100', 'S', '1100', 'Floral Print Dress Casual Cute Solid V Neck Dalmatian Ruffle Trim Tie Boho Beach High Waist Mini Dresses Women Fit and Flare Multicolor Dress.')";
$con->query($w1);
$w2 = "insert into womenwear values('wwc1p1sm', 'assets/11.jpeg', 'Mini Dress', '2100', 'M', '1100', 'Floral Print Dress Casual Cute Solid V Neck Dalmatian Ruffle Trim Tie Boho Beach High Waist Mini Dresses Women Fit and Flare Multicolor Dress.')";
$con->query($w2);
$w3 = "insert into womenwear values('wwc1p1sl', 'assets/11.jpeg', 'Mini Dress', '2100', 'L', '1100', 'Floral Print Dress Casual Cute Solid V Neck Dalmatian Ruffle Trim Tie Boho Beach High Waist Mini Dresses Women Fit and Flare Multicolor Dress.')";
$con->query($w3);
$w4 = "insert into womenwear values('wwc1p2ss', 'assets/12.jpeg', 'Vacation Halter Printed Sleeveless Dress', '2500', 'S', '1100', 'Halter neck style sleeveless detachable waist gathered tiered skirt panels invisible back zip neck opening.')";
$con->query($w4);
$w5 = "insert into womenwear values('wwc1p2sm', 'assets/12.jpeg', 'Vacation Halter Printed Sleeveless Dress', '2500', 'M', '1100', 'Halter neck style sleeveless detachable waist gathered tiered skirt panels invisible back zip neck opening.')";
$con->query($w5);
$w6 = "insert into womenwear values('wwc1p2sl', 'assets/12.jpeg', 'Vacation Halter Printed Sleeveless Dress', '2500', 'L', '1100', 'Halter neck style sleeveless detachable waist gathered tiered skirt panels invisible back zip neck opening.')";
$con->query($w6);
$w7 = "insert into womenwear values('wwc1p3ss', 'assets/1.jpeg', 'Selous Slip Mini Dress', '2700', 'S',  '1100', 'The Selous Slip Mini Dress Blue Daisy was made for a night out with the girls!! This mini dress will have you feeling fun and fresh on a warm summers night.')";
$con->query($w7);
$w8 = "insert into womenwear values('wwc1p3sm', 'assets/1.jpeg', 'Selous Slip Mini Dress', '2700', 'M', '1100', 'The Selous Slip Mini Dress Blue Daisy was made for a night out with the girls!! This mini dress will have you feeling fun and fresh on a warm summers night.')";
$con->query($w8);
$w9 = "insert into womenwear values('wwc1p3sl', 'assets/1.jpeg', 'Selous Slip Mini Dress', '2700', 'L', '1100', 'The Selous Slip Mini Dress Blue Daisy was made for a night out with the girls!! This mini dress will have you feeling fun and fresh on a warm summers night.')";
$con->query($w9);
$w10 = "insert into womenwear values('wwc2p1ss', 'assets/8.jpg', 'Cut Out Crop Tank Top', '3000', 'S', '1100', 'Dazzle this summer with this striped blue crop top from People. Crafted from pure cotton, this design features noodle straps. Team it with shorts and flats for a chic look .')";
$con->query($w10);
$w11 = "insert into womenwear values('wwc2p1sm', 'assets/8.jpg', 'Cut Out Crop Tank Top', '3000', 'M', '1100', 'Dazzle this summer with this striped blue crop top from People. Crafted from pure cotton, this design features noodle straps. Team it with shorts and flats for a chic look .')";
$con->query($w11);
$w12 = "insert into womenwear values('wwc2p1sl', 'assets/8.jpg', 'Cut Out Crop Tank Top', '3000', 'L', '1100', 'Dazzle this summer with this striped blue crop top from People. Crafted from pure cotton, this design features noodle straps. Team it with shorts and flats for a chic look .')";
$con->query($w12);
$w13 = "insert into womenwear values('wwc2p2ss', 'assets/9.jpg', 'Mint for Spring – The Cutest Eyelet Top!', '2800', 'S', '1100', 'It feels so fresh and happy especially when paired with white. This outfit is perfect for so many occasions Backless Printed Halter Dress For Vacation in Green.')";
$con->query($w13);
$w14 = "insert into womenwear values('wwc2p2sm', 'assets/9.jpg', 'Mint for Spring – The Cutest Eyelet Top!', '2800', 'M', '1100', 'It feels so fresh and happy especially when paired with white. This outfit is perfect for so many occasions Backless Printed Halter Dress For Vacation in Green.')";
$con->query($w14);
$w15 = "insert into womenwear values('wwc2p2sl', 'assets/9.jpg', 'Mint for Spring – The Cutest Eyelet Top!', '2800', 'L', '1100', 'It feels so fresh and happy especially when paired with white. This outfit is perfect for so many occasions Backless Printed Halter Dress For Vacation in Green.')";
$con->query($w15);
$w16 = "insert into womenwear values('wwc2p3ss', 'assets/10.jpg', 'Macy Fit And Flare Wrap Top Blue', '3200', 'S', '1100', 'Featuring long bishop style sleeves, V-neckline that wraps under the bust and fastens with a ribbon tie at the side Print Cold Shoulder Top.')";
$con->query($w16);
$w17 = "insert into womenwear values('wwc2p3sm', 'assets/10.jpg', 'Macy Fit And Flare Wrap Top Blue', '3200', 'M', '1100', 'Featuring long bishop style sleeves, V-neckline that wraps under the bust and fastens with a ribbon tie at the side Print Cold Shoulder Top.')";
$con->query($w17);
$w18 = "insert into womenwear values('wwc2p3sl', 'assets/10.jpg', 'Macy Fit And Flare Wrap Top Blue', '3200', 'L', '1100', 'Featuring long bishop style sleeves, V-neckline that wraps under the bust and fastens with a ribbon tie at the side Print Cold Shoulder Top.')";
$con->query($w18);
$w19 = "insert into womenwear values('wwc3p1ss', 'assets/2.jpg', 'Golden Bordered Peach Chakori Saree', '4200', 'S', '1100', 'Collection of the Latest Banarasi Sarees to amp up your saree game Chakori Ethnic Chanderi Saree.')";
$con->query($w19);
$w20 = "insert into womenwear values('wwc3p1sm', 'assets/2.jpg', 'Golden Bordered Peach Chakori Saree', '4200', 'M', '1100', 'Collection of the Latest Banarasi Sarees to amp up your saree game Chakori Ethnic Chanderi Saree.')";
$con->query($w20);
$w21 = "insert into womenwear values('wwc3p1sl', 'assets/2.jpg', 'Golden Bordered Peach Chakori Saree', '4200', 'L', '1100', 'Collection of the Latest Banarasi Sarees to amp up your saree game Chakori Ethnic Chanderi Saree.')";
$con->query($w21);
$w22 = "insert into womenwear values('wwc3p2ss', 'assets/3.jpg', 'Ruffled Saree', '4000', 'S', '1100', 'Steal the show with these gorgeous ruffled sarees. Ruffled saree ideas for wedding and more inspirations for wedding.')";
$con->query($w22);
$w23 = "insert into womenwear values('wwc3p2sm', 'assets/3.jpg', 'Ruffled Saree', '4000', 'M', '1100', 'Steal the show with these gorgeous ruffled sarees. Ruffled saree ideas for wedding and more inspirations for wedding.')";
$con->query($w23);
$w24 = "insert into womenwear values('wwc3p2sl', 'assets/3.jpg', 'Ruffled Saree', '4000', 'L', '1100', 'Steal the show with these gorgeous ruffled sarees. Ruffled saree ideas for wedding and more inspirations for wedding.')";
$con->query($w24);
$w25 = "insert into womenwear values('wwc3p3ss', 'assets/4.jpg', 'Gulzar Feriha Kurta', '3500', 'S', '1100', 'Adorned with tones of blue and green against the serenity of white, it comes embellished with delicate sequins work on the yoke.')";
$con->query($w25);
$w26 = "insert into womenwear values('wwc3p3sm', 'assets/4.jpg', 'Gulzar Feriha Kurta', '3500', 'M', '1100', 'Adorned with tones of blue and green against the serenity of white, it comes embellished with delicate sequins work on the yoke.')";
$con->query($w26);
$w27 = "insert into womenwear values('wwc3p3sl', 'assets/4.jpg', 'Gulzar Feriha Kurta', '3500', 'L', '1100', 'Adorned with tones of blue and green against the serenity of white, it comes embellished with delicate sequins work on the yoke.')";
$con->query($w27);
$w28 = "insert into womenwear values('wwc4p1ss', 'assets/5.jpg', 'Cobain Pants', '2500', 'S', '1100', 'Lightweight suiting Optional chain accent Houndstooth plaid pattern pants.')";
$con->query($w28);
$w29 = "insert into womenwear values('wwc4p1sm', 'assets/5.jpg', 'Cobain Pants', '2500', 'M', '1100', 'Lightweight suiting Optional chain accent Houndstooth plaid pattern pants.')";
$con->query($w29);
$w30 = "insert into womenwear values('wwc4p1sl', 'assets/5.jpg', 'Cobain Pants', '2500', 'L', '1100', 'Lightweight suiting Optional chain accent Houndstooth plaid pattern pants.')";
$con->query($w30);
$w31 = "insert into womenwear values('wwc4p2ss', 'assets/7.jpg', 'Ribbon design Pants', '2700', 'S', '1100', 'This pants feature a side pockets and letter print design.amde by natural synthetic comfortable design.')";
$con->query($w31);
$w32 = "insert into womenwear values('wwc4p2sm', 'assets/7.jpg', 'Ribbon design Pants', '2700', 'M', '1100', 'This pants feature a side pockets and letter print design.amde by natural synthetic comfortable design.')";
$con->query($w32);
$w33 = "insert into womenwear values('wwc4p2sl', 'assets/7.jpg', 'Ribbon design Pants', '2700', 'L', '1100', 'This pants feature a side pockets and letter print design.amde by natural synthetic comfortable design.')";
$con->query($w33);
$w34 = "insert into womenwear values('wwc4p3ss', 'assets/6.jpg', 'Streatwear Jumpsuit', '2800', 'S', '1100', 'Red Camouflage Print Pockets Camo High Waisted Streetwear Long Jumpsuit High-Rise Checked Pants.')";
$con->query($w34);
$w35 = "insert into womenwear values('wwc4p3sm', 'assets/6.jpg', 'Streatwear Jumpsuit', '2800', 'M', '1100', 'Red Camouflage Print Pockets Camo High Waisted Streetwear Long Jumpsuit High-Rise Checked Pants.')";
$con->query($w35);
$w36 = "insert into womenwear values('wwc4p3sl', 'assets/6.jpg', 'Streatwear Jumpsuit', '2800', 'L', '1100', 'Red Camouflage Print Pockets Camo High Waisted Streetwear Long Jumpsuit High-Rise Checked Pants.')";
$con->query($w36);
?>